on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  release:

name: Render project

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      NETLIFY_SITE_ID: e3c5b1f9-4e9e-46c1-9da1-cf73bbaab4d5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.340
          tinytex: true

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      
      ## push actions
      - name: Deploy push
        uses: data-intuitive/netlify-deploy-site@v1
        if: github.event_name == 'push'
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site: ${{ env.NETLIFY_SITE_ID }}
          dir: '_site'
          prod: true
          message: 'Deploy main ${{ github.ref }}'

      ## PR actions
      - name: Deploy preview
        id: deploy_preview
        if: github.event_name == 'pull_request'
        uses: data-intuitive/netlify-deploy-site@v1
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site: ${{ env.NETLIFY_SITE_ID }}
          dir: '_site'
          alias: "${{ env.BRANCH_NAME }}"
          message: 'Deploy preview ${{ github.ref }}'

      - name: Comment on PR (success)
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            [![Deploy: success](https://img.shields.io/badge/Deploy-success-success)](${{ steps.deploy_preview.outputs.deploy-url }})
          comment_tag: deploy_status

      - name: Comment on PR (actions failure)
        uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && failure()
        with:
          message: |
            [![Deploy: failure](https://img.shields.io/badge/Deploy-failure-critical)](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/jobs/${{github.job}})
          comment_tag: deploy_status
  
